services:
  db:
    image: mysql:8
    restart: always
    networks:
      - backend
    env_file: ./mysql/mysql.env
    ports:
      - 3306:3306
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
  app:
    image: node:18
    restart: always
    working_dir: /app
    tty: true
    networks:
      - backend
    command: bash -c "npm install && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 24459:24459
      - 8000:8000
    depends_on:
      - db
    
networks:
  backend:
