import { useSession } from "next-auth/react";
import Head from "next/head";
import Book from "~/components/Book";
import { Header } from "~/components/Header";
import { api } from "~/utils/api";

export default function Home() {
  const { data: session } = useSession();

  const { data: books, refetch: refetchBooks } = api.book.getAll.useQuery(
    undefined,
    { enabled: session?.user !== undefined, retry: true },
  );
  return (
    <>
      <Head>
        <title>mdbook - Markdown book memo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen min-w-fit">
        <Header />
        {books?.map((book: Book) => <Book key={book.id + book.title} {...book} />)}
      </main>
    </>
  );
}
