import { useSession } from "next-auth/react";
import Head from "next/head";
import { Header } from "~/components/Header";
import { type Book } from "@prisma/client";

import { api } from "~/utils/api";

export default function Home() {
  const { data: session } = useSession();

  const { data: books, refetch: refetchBooks } = api.book.getAll.useQuery(
    undefined,
    { enabled: session?.user !== undefined, retry: true },
  );

  return (
    <>
      <Head>
        <title>mdbook - Markdown book memo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen min-w-fit">
        <Header />
        {books?.map((book: Book) => (
          <div key={book.id}>
            <div>{book.title}</div>
            <div>{book.description}</div>
            <div>{book.author ?? ""}</div>
            <div>{book.coverImage ?? ""}</div>
            <div>{book.content}</div>
          </div>
        ))}
        {/* className="flex min-h-screen flex-col items-center justify-center" */}
      </main>
    </>
  );
}
